[[events]]
id = 1
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-04-18"
venueId = "pha"
image = "assets/media/PHADrone.jpg"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

### Schedule
- Setup: 8:00
- New Shooters Meeting: 9:30
- General Safety Meeting: 10:00

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 5
- Round Count (estimated): 100 carbine + 100 handgun
- Match Fee: $35

### Divisions
- Competition
- Practical

New to action shooting or two-gun? Sign up as "Practical" and bring:
- Rifle or PCC with sling, caliber no greater than `.308`
- Handgun with a safe holster -- No SERPA or Uncle Mike's style fabric holsters
- 3 magazines for each firearm

**Use of M855 / SS109 or similar ammo is prohibited.**

### Rules & Scoring
PCSL General Rulebook, current revision, using Hit Factor (Points Per Second).

Rulebook: [pcsleague.us](https://www.pcsleague.us/)

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.
"""
registerUrl = "https://practiscore.com/pcsl-two-gun-at-pha-3/register"

[[events]]
id = 2
type = "low-light"
name = "PCSL One Gun - Low Light"
date = "2026-04-19"
venueId = "bellevue-indoor"
image = "assets/media/bir.jpg"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

Come out to Bellevue Indoor Range for a 4-stage Low Light PCSL match!

Given the reduced lighting conditions, we require participants to have attended at least 3 events with CASS to ensure familiarity with action shooting safety rules and match etiquette.

### Schedule
YOU MUST CHECK IN AT RANGE DESK TO FILL OUT WAIVER.
ANYONE NEW TO BELLEVUE INDOOR RANGE IS REQUIRED TO ATTEND THE NEW SHOOTER ORIENTATION REGARDLESS OF EXPERIENCE LEVEL.

- Setup: 9:00
- New Shooters Meeting: 9:45
- General Safety Meeting: 10:15

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 4
- Round Count (estimated): 100 carbine + 100 handgun

### Required Equipment
- Night Vision Division: Night vision device & familiarity
- White light on ALL firearms AND handheld flashlight
- Electronic Hearing Protection
- Rifle with sling and 3 magazines (Caliber no greater than `7.62x39` / `300BLK`)
- Handgun with a safe holster and 3 magazines -- No SERPA or Uncle Mike's style fabric holsters
- **Muzzle brakes / compensators / ports are prohibited** unless used as a suppressor host

**Use of M855 / SS109 / M855A1 or similar ammo is strictly prohibited.**

### Bellevue Indoor Range SOP
- Use of a Sig P320 in any form is prohibited.
- Participant will be ejected and prohibited from attending any events if M855 / SS109 / M855A1 is found on premises.
- No food or drink allowed in the action bays.

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.
"""
registerUrl = "https://practiscore.com/bellevue-indoor-range-pcsl-low-light/register"

[[events]]
id = 3
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-04-25"
venueId = "svrc"
image = "assets/media/DSC_1112.jpg"
spots = 60
desc = """
## General Match Info

Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

## Schedule

- Setup: 8:00
- New Shooters Meeting: 9:30
- General Safety Meeting: 10:00

**You will not be allowed to shoot if you miss the safety meeting.**

## Match Details

- **Stages:** 5
- **Round Count (estimated):** 100 carbine + 100 handgun
- **Match Fee:** $35

## Divisions

- Competition
- Practical

New to action shooting or two-gun? Sign up as **Practical** and bring:

- Rifle or PCC with sling, caliber no greater than `.308`
- Handgun with a safe holster -- No SERPA or Uncle Mike's style fabric holsters
- 3 magazines for each firearm

**Use of M855 / SS109 or similar ammo is prohibited.**

## Rules & Scoring

PCSL General Rulebook, current revision, using **Hit Factor (Points Per Second)**.

Rulebook: [pcsleague.us](https://www.pcsleague.us/)

## Refund Policy

Full refunds are available for withdrawal requests made through the **Saturday prior to match date**.

Refunds issued will be less Stripe's **3% processing fee**.
"""
registerUrl = "https://practiscore.com/april-two-gun-at-svrc-1/register"

[[events]]
id = 4
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-05-16"
venueId = "jcsa"
image = "assets/media/jcsaretina-300x297.png"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

### Schedule
- Setup: 8:00
- New Shooters Meeting: 9:30
- General Safety Meeting: 10:00

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 6
- Round Count (estimated): 120 carbine + 120 handgun
- Match Fee: $35

### Divisions
- Competition
- Practical

New to action shooting or two-gun? Sign up as "Practical" and bring:
- Rifle or PCC with sling, caliber no greater than `.308`
- Handgun with a safe holster -- No SERPA or Uncle Mike's style fabric holsters
- 3 magazines for each firearm

**Use of M855 / SS109 or similar ammo is prohibited.**

### Rules & Scoring
PCSL General Rulebook, current revision, using Hit Factor (Points Per Second).

**Range SOP:** Slung rifles may not break the 180 regardless of condition (incl inert PCSL 1.4.2.3); slung rifles are allowed the same 3’ radius exception as handguns.

Rulebook: [pcsleague.us](https://www.pcsleague.us/)

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.

### Venue
[Jefferson County Sportsman's Association](https://jeffersoncountysportsmen.org/)  
112 Gun Club Rd, Port Townsend, WA 98368  
[Get Directions](https://www.google.com/maps/dir//112+Gun+Club+Rd,+Port+Townsend,+WA+98368)
"""
registerUrl = "https://practiscore.com/port-townsend-pcsl-2-gun-event-by-cascade-action-may/register"

[[events]]
id = 5
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-05-17"
venueId = "bellevue-indoor"
image = "assets/media/bir.jpg"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

Come out to Bellevue Indoor Range for a 4-stage Low Light PCSL match!

Given the reduced lighting conditions, we require participants to have attended at least 3 events with CASS to ensure familiarity with action shooting safety rules and match etiquette.

### Schedule
YOU MUST CHECK IN AT RANGE DESK TO FILL OUT WAIVER.
ANYONE NEW TO BELLEVUE INDOOR RANGE IS REQUIRED TO ATTEND THE NEW SHOOTER ORIENTATION REGARDLESS OF EXPERIENCE LEVEL.

- Setup: 9:00
- New Shooters Meeting: 9:45
- General Safety Meeting: 10:15

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 4
- Round Count (estimated): 100 carbine + 100 handgun

### Required Equipment
- Night Vision Division: Night vision device & familiarity
- White light on ALL firearms AND handheld flashlight
- Electronic Hearing Protection
- Rifle with sling and 3 magazines (Caliber no greater than `7.62x39` / `300BLK`)
- Handgun with a safe holster and 3 magazines -- No SERPA or Uncle Mike's style fabric holsters
- **Muzzle brakes / compensators / ports are prohibited** unless used as a suppressor host

**Use of M855 / SS109 / M855A1 or similar ammo is strictly prohibited.**

### Bellevue Indoor Range SOP
- Use of a Sig P320 in any form is prohibited.
- Participant will be ejected and prohibited from attending any events if M855 / SS109 / M855A1 is found on premises.
- No food or drink allowed in the action bays.

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.
"""
registerUrl = "https://practiscore.com/bellevue-indoor-range-pcsl-two-gun-5/register"

[[events]]
id = 6
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-05-23"
venueId = "pha"
image = "assets/media/PHADrone.jpg"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

### Schedule
- Setup: 8:00
- New Shooters Meeting: 9:30
- General Safety Meeting: 10:00

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 5
- Round Count (estimated): 100 carbine + 100 handgun
- Match Fee: $35

### Divisions
- Competition
- Practical

New to action shooting or two-gun? Sign up as "Practical" and bring:
- Rifle or PCC with sling, caliber no greater than `.308`
- Handgun with a safe holster -- No SERPA or Uncle Mike's style fabric holsters
- 3 magazines for each firearm

**Use of M855 / SS109 or similar ammo is prohibited.**

### Rules & Scoring
PCSL General Rulebook, current revision, using Hit Factor (Points Per Second).

Rulebook: [pcsleague.us](https://www.pcsleague.us/)

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.
"""
registerUrl = "https://practiscore.com/pcsl-two-gun-at-pha-2/register"

[[events]]
id = 7
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-05-30"
venueId = "svrc"
image = "assets/media/DSC_1112.jpg"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

### Schedule
- Setup: 8:00
- New Shooters Meeting: 9:30
- General Safety Meeting: 10:00

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 5
- Round Count (estimated): 100 carbine + 100 handgun
- Match Fee: $35

### Divisions
- Competition
- Practical

New to action shooting or two-gun? Sign up as "Practical" and bring:
- Rifle or PCC with sling, caliber no greater than `.308`
- Handgun with a safe holster -- No SERPA or Uncle Mike's style fabric holsters
- 3 magazines for each firearm

**Use of M855 / SS109 or similar ammo is prohibited.**

### Rules & Scoring
PCSL General Rulebook, current revision, using Hit Factor (Points Per Second).

Rulebook: [pcsleague.us](https://www.pcsleague.us/)

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.
"""
registerUrl = "https://practiscore.com/may-two-gun-at-svrc-1/register"

[[events]]
id = 8
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-06-07"
venueId = "bellevue-indoor"
image = "assets/media/bir.jpg"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

Come out to Bellevue Indoor Range for a 4-stage Low Light PCSL match!

Given the reduced lighting conditions, we require participants to have attended at least 3 events with CASS to ensure familiarity with action shooting safety rules and match etiquette.

### Schedule
YOU MUST CHECK IN AT RANGE DESK TO FILL OUT WAIVER.
ANYONE NEW TO BELLEVUE INDOOR RANGE IS REQUIRED TO ATTEND THE NEW SHOOTER ORIENTATION REGARDLESS OF EXPERIENCE LEVEL.

- Setup: 9:00
- New Shooters Meeting: 9:45
- General Safety Meeting: 10:15

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 4
- Round Count (estimated): 100 carbine + 100 handgun

### Required Equipment
- Night Vision Division: Night vision device & familiarity
- White light on ALL firearms AND handheld flashlight
- Electronic Hearing Protection
- Rifle with sling and 3 magazines (Caliber no greater than `7.62x39` / `300BLK`)
- Handgun with a safe holster and 3 magazines -- No SERPA or Uncle Mike's style fabric holsters
- **Muzzle brakes / compensators / ports are prohibited** unless used as a suppressor host

**Use of M855 / SS109 / M855A1 or similar ammo is strictly prohibited.**

### Bellevue Indoor Range SOP
- Use of a Sig P320 in any form is prohibited.
- Participant will be ejected and prohibited from attending any events if M855 / SS109 / M855A1 is found on premises.
- No food or drink allowed in the action bays.

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.
"""
registerUrl = "https://practiscore.com/bellevue-indoor-range-pcsl-two-gun-6/register"

[[events]]
id = 9
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-06-27"
venueId = "svrc"
image = "assets/media/DSC_1112.jpg"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

### Schedule
- Setup: 8:00
- New Shooters Meeting: 9:30
- General Safety Meeting: 10:00

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 5
- Round Count (estimated): 100 carbine + 100 handgun
- Match Fee: $35

### Divisions
- Competition
- Practical

New to action shooting or two-gun? Sign up as "Practical" and bring:
- Rifle or PCC with sling, caliber no greater than `.308`
- Handgun with a safe holster -- No SERPA or Uncle Mike's style fabric holsters
- 3 magazines for each firearm

**Use of M855 / SS109 or similar ammo is prohibited.**

### Rules & Scoring
PCSL General Rulebook, current revision, using Hit Factor (Points Per Second).

Rulebook: [pcsleague.us](https://www.pcsleague.us/)

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.
"""
registerUrl = "https://practiscore.com/june-two-gun-at-svrc-2/register"

[[events]]
id = 10
type = "two-gun"
name = "PCSL Two Gun"
date = "2026-07-11"
venueId = "jcsa"
image = "assets/media/jcsaretina-300x297.png"
spots = 60
desc = """
### General Match Info
Contact: [info@cascadeaction.org](mailto:info@cascadeaction.org)  
FAQ: [cascadeaction.org/pages/faq](https://cascadeaction.org/pages/faq)

### Schedule
- Setup: 8:00
- New Shooters Meeting: 9:30
- General Safety Meeting: 10:00

**You will not be allowed to shoot if you miss the safety meeting.**

### Match Details
- Stages: 6
- Round Count (estimated): 120 carbine + 120 handgun
- Match Fee: $35

### Divisions
- Competition
- Practical

New to action shooting or two-gun? Sign up as "Practical" and bring:
- Rifle or PCC with sling, caliber no greater than `.308`
- Handgun with a safe holster -- No SERPA or Uncle Mike's style fabric holsters
- 3 magazines for each firearm

**Use of M855 / SS109 or similar ammo is prohibited.**

### Rules & Scoring
PCSL General Rulebook, current revision, using Hit Factor (Points Per Second).

**Range SOP:** Slung rifles may not break the 180 regardless of condition (incl inert PCSL 1.4.2.3); slung rifles are allowed the same 3’ radius exception as handguns.

Rulebook: [pcsleague.us](https://www.pcsleague.us/)

### Refund Policy
Full refunds are available for withdrawal requests made through the Saturday prior to match date.

Refunds issued will be less Stripe's 3% processing fee.

### Venue
[Jefferson County Sportsman's Association](https://jeffersoncountysportsmen.org/)  
112 Gun Club Rd, Port Townsend, WA 98368  
[Get Directions](https://www.google.com/maps/dir//112+Gun+Club+Rd,+Port+Townsend,+WA+98368)
"""
registerUrl = "https://practiscore.com/port-townsend-pcsl-2-gun-event-by-cascade-action-july/register"
