name = "practiscore-scraper"
main = "index.js"
compatibility_date = "2026-04-04"
compatibility_flags = ["nodejs_compat"]

# Browser Rendering binding
[browser]
binding = "BROWSER"

# KV Database for Caching
[[kv_namespaces]]
binding = "MATCH_DATA"
id = "f06e1acee402409aaf9b39d9bc1f87e3"

# Automatic background updates every 2 hours
[triggers]
crons = ["0 */2 * * *"]

[vars]
CASS_SITE_URL = "https://cass.cass-account.workers.dev"
